-- Supabase schema: documents table with pgvector
create extension if not exists vector;

create table if not exists documents (
  id bigint generated by default as identity primary key,
  text text,
  source text,
  url text,
  embedding vector(1536),
  inserted_at timestamptz default now()
);

-- Example match function using pgvector
create or replace function public.match_documents(query_embedding vector, match_count int)
returns table(id bigint, text text, source text, url text, score float)
language sql stable as $$
  select id, text, source, url, 1 - (embedding <=> query_embedding) as score
  from documents
  order by embedding <=> query_embedding
  limit match_count;
$$;
